<a href="https://colab.research.google.com/github/sahoop2002/PRATIP-SAHOO/blob/main/NUMPY_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
y=([1,2,3,4])
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

The slowest run took 5.39 times longer than the fastest. This could mean that an intermediate result is being cached.
1.56 µs ± 928 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
import numpy as np
%timeit np.arange(1,9)**4

2.03 µs ± 415 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# ARRAYS


In [9]:
import numpy as np

x=[1,2,3,4]
#y= np.array(x)
y=np.array([1,2,3,4,5])
#print(y)
#y
print(type(y))
print (y.ndim)

<class 'numpy.ndarray'>
1


In [10]:
l = []
for i in range (1,5):
  int_1 = int(input ("enter :"))
  l.append(int_1)
print(np.array(l))

enter :12
enter :11
enter :13
enter :10
[12 11 13 10]


In [11]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)  # ndim is a function to know the dimensions of the array


[[1 2 3 4]
 [5 6 7 8]]
2


In [12]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [13]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


**ARRAY FILLED WITH ZERO**

In [14]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**ARRAY FILLED WITH ONES**


In [15]:
ar_ones = np.ones(4)
print(ar_ones)

[1. 1. 1. 1.]


**EMPTY ARRAY**

In [16]:
ar_em=np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


**ARRAY OF A RANGE**

In [17]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


**ARREY DIAGONAL ELEMENT FILLED WITH ONES**

In [18]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


**LINSPACE ARRAY**

In [20]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# *CREATE NUMPY ARRAYS WITH RANDOM NUMBERS*

**rand()**

In [21]:
import numpy as np


var = np.random.rand(3)
print(var)

[0.33003365 0.50003726 0.74572795]


**randn()**

In [22]:
var1 = np.random.randn(5)
print(var1)

[ 0.92108805 -0.59756217 -1.27831724 -0.10613395  0.49257659]


In [23]:
var2 = np.random.randn(2,3)
print(var2)

[[-0.45190201 -1.29142916  0.24196831]
 [-0.35975007 -0.50468964 -2.51735918]]


**ranf()**

In [24]:
var3=np.random.ranf(4)
print(var3)

[0.04578904 0.10255449 0.74303705 0.8491101 ]


**randint()**

In [25]:
var4 = np.random.randint(10,30,7)
print(var4)

[26 19 25 20 20 13 16]


# DATA TYPES IN NUMPY ARRAY

In [26]:
import numpy as np
var = np.array([1,2,3,4])
print ("Data Type :", var.dtype)


Data Type : int64


In [27]:
import numpy as np


var = np.array([1.0,1.4,1.6,2.3,2.7])

print ("Data Type :", var.dtype)

Data Type : float64


In [28]:
import numpy as np


var = np.array(["A","B","X","Y"])

print ("Data Type :", var.dtype)

Data Type : <U1


In [29]:
import numpy as np


var = np.array(["A","S","D","F",1,2,3,4])

print ("Data Type : ", var.dtype)

Data Type :  <U21


In [30]:
x = np.array([1,2,3,4],dtype = np.int8)
print ("Data Type :", x.dtype)

Data Type : int8


In [31]:
x1 = np.array([1,2,3,4],dtype = "f")
print ("Data Type :", x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


In [32]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)

print ("Data Type :", x2.dtype)
print ("Data Type :", new.dtype)
print(x2)
print(new)

Data Type : int64
Data Type : float32
[1 2 3 4]
[1. 2. 3. 4.]


In [33]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)
#print ("Data Type :", x3.dtype)
#print ("Data Type :", new_1.dtype)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


# SHAPE AND RESHAPING IN NUMPY ARRAY

**SHAPE**

In [34]:
import numpy as np


var = np.array ([[1,2,3,4],[5,6,7,8]])
print (var)
print()
print(var.shape)

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


In [35]:
var1 = np.array ([1,2,3,4],ndmin=4)
print (var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


**RESHAPE**

In [36]:
var2 = np.array([1,2,3,4,5,6,7,8,9])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 7 8 9]
1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [37]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(3,2,3)
print(x1)
print(x1.ndim)

print()


one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1


#ARITHMATIC OPERATIONS IN NUMPY ARRAY
we can use these functions to perform the operations :
1. a+b --- np.add(a+b)
2. a-b --- np.subtract(a+b)
3. a*b --- np.multiply(a+b)
4. a/b --- np.devide(a+b)
5. a%b --- np.mod(a+b)
6. a**b --- np.power(a+b)
7. 1/a --- np.reciprocal(a)

In [38]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [39]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1+var2
print(varadd)

[2 4 6 8]


In [40]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [41]:
var = np.array([1,2,3,4])
varadd = var - 3
print(varadd)

[-2 -1  0  1]


In [42]:
var = np.array([1,2,3,4])
varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [43]:
var = np.array([1,2,3,4])
varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [44]:
var = np.array([1,2,3,4])
varadd = var % 3
print(varadd)

[1 2 0 1]


In [45]:
var = np.array([1,2,3,4])
varadd = var ** 3
print(varadd)

[ 1  8 27 64]


In [46]:
var = np.array([1,2,3,4])
var2 = np.reciprocal(var)
print(var2)

[1 0 0 0]


**2D ARRAY**

In [47]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd = np.add(var21,var22)
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


**MORE ARITHMATIC FUNCTIONS**

1. np.min(x)
2. np.max(x)
3. np.argmin(x)   [to define position]    
4. np.sqrt(x)
5. np.sin(x)
6. np.cos(x)
7. np.cumsum(x)   [cumsum = community sum]

In [69]:
import numpy as np

var = np.array([-1,92,3,4,24,67,-8])

print ("Min :", np.min(var), np.argmin(var))
print ("Max :", np.max(var), np.argmax(var))

print ("Sqrt :", np.sqrt(var))

print ("Sin :", np.sin(var))
print ("Cos :", np.cos(var))

print ("Cumsum :", np.cumsum(var))

Min : -8 6
Max : 92 1
Sqrt : [       nan 9.59166305 1.73205081 2.         4.89897949 8.18535277
        nan]
Sin : [-0.84147098 -0.77946607  0.14112001 -0.7568025  -0.90557836 -0.85551998
 -0.98935825]
Cos : [ 0.54030231 -0.62644445 -0.9899925  -0.65364362  0.42417901 -0.5177698
 -0.14550003]
Cumsum : [ -1  91  94  98 122 189 181]


/tmp/ipython-input-4164695212.py:8: RuntimeWarning: invalid value encountered in sqrt
  print ("Sqrt :", np.sqrt(var))


In [49]:
var1 = np.array([[4,17,3,35],[67,8,2,18]])
print(np.min(var1,axis=0))
print()
print(np.min(var1,axis=1))

[ 4  8  2 18]

[3 2]


In [68]:
var2 = np.array([[[4,17,3,35],[67,8,2,18],[89,-2,11,102]]])
print(np.min(var2,axis=0))
print()
print(np.min(var2,axis=1))
print()
print(np.min(var2,axis=2))

[[  4  17   3  35]
 [ 67   8   2  18]
 [ 89  -2  11 102]]

[[ 4 -2  2 18]]

[[ 3  2 -2]]


# BROADCASTING NUMPY ARRAYS

In [67]:
import numpy as np

var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()



var2 = np.array ([[5],[6],[8]])
print(var2.shape)
print()
print(var2)
print()

print(var1+var2)




(3,)

[1 2 3]

(3, 1)

[[5]
 [6]
 [8]]

[[ 6  7  8]
 [ 7  8  9]
 [ 9 10 11]]


In [66]:
x = np.array([[1],[2]])
print(x)
print(x.shape)
print()
y = np.array([[1,2,3],[7,8,9]])
print(y)
print(y.shape)
print()
print(x+y)
print((x+y).shape)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [7 8 9]]
(2, 3)

[[ 2  3  4]
 [ 9 10 11]]
(2, 3)


#INDEXING & SLICING IN NUMPY ARRAYS

In [53]:
import numpy as np


var = np.array([9,8,7,6])
# indexing      0 1 2 3
# - indexing. -4,-3,-2,-1


print(var[0])
print(var[1])
print(var[-3])

9
8
8


In [54]:
var1  = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [55]:
var2 = np.array([[[1,2,4],[3,4,7]],[[3,5,6],[1,7,8]]])
print(var2)
print()
print(var2.shape)
print()
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2 4]
  [3 4 7]]

 [[3 5 6]
  [1 7 8]]]

(2, 2, 3)

3

4


**SLICING**

**1D**

In [65]:
var = np.array([9,8,7,6,3,16,34,62,29])
# index         0 1 2 3 4 5  6  7  8
print(var)
print()
print("2 to 5 :", var[1:5] )    # stop point : if i want value of 2 to 5 then stop point should be 6
print()
print("2 to end :", var[3:])
print()
print("start to 5 :", var[:6])
print()
print("step point :",var[::2])

[ 9  8  7  6  3 16 34 62 29]

2 to 5 : [8 7 6 3]

2 to end : [ 6  3 16 34 62 29]

start to 5 : [ 9  8  7  6  3 16]

step point : [ 9  7  3 34 29]


**2D**

In [64]:
var1  = np.array([[9,68,27,11,34,78,102],[43,15,66,89,77,9,20]])
print(var1)
print()
print(var1[0,2:6])
print()
print(var1[0,1:6])
print()
print(var1[0,2:6:2])
print()
print(var1[1,1:6:2])

[[  9  68  27  11  34  78 102]
 [ 43  15  66  89  77   9  20]]

[27 11 34 78]

[68 27 11 34 78]

[27 34]

[15 89  9]


**3D**

In [63]:
var5 = np.array([[[1,22,43,56,89,77,12,27,8,33],[30,4,47,87,90,31,67,18,6,2]],[[34,48,33,79,42,55,15,68,10,90],[13,97,58,93,39,78,25,45,8,17]]])
print(var5)
print()
print(var5[1,1:6:2])
print()
print(var5[0,1,2:9:2])
print()
print(var5[0,0,1:9:2])

[[[ 1 22 43 56 89 77 12 27  8 33]
  [30  4 47 87 90 31 67 18  6  2]]

 [[34 48 33 79 42 55 15 68 10 90]
  [13 97 58 93 39 78 25 45  8 17]]]

[[13 97 58 93 39 78 25 45  8 17]]

[47 90 67  6]

[22 56 77 27]


# ITERATING NUMPY ARRAYS

In [60]:
import numpy as np


var = np.array ([9,8,7,6,5,4])
print (var)
print()
for i in var :
  print (i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [62]:
var1  = np.array([[9,8,7,4],[4,5,6,3]])
print(var1)
print()
for j in var1:
  print(j)

print()
for k in var1:
  for l in k:
    print(l)


[[9 8 7 4]
 [4 5 6 3]]

[9 8 7 4]
[4 5 6 3]

9
8
7
4
4
5
6
3


In [72]:
var3 = np.array([[[1,2,4],[3,4,7]],[[3,5,6],[1,7,8]]])
print(var3)
print(var3.ndim)
print()


for j in var3:
  for k in j:
    for l in k :
      print(l)

[[[1 2 4]
  [3 4 7]]

 [[3 5 6]
  [1 7 8]]]
3

1
2
4
3
4
7
3
5
6
1
7
8


**nditer() function**

In [73]:
var3 = np.array([[[1,2,4],[3,4,7]],[[3,5,6],[1,7,8]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
  print(i)

[[[1 2 4]
  [3 4 7]]

 [[3 5 6]
  [1 7 8]]]
3

1
2
4
3
4
7
3
5
6
1
7
8


In [74]:
var3 = np.array([[[1,2,4],[3,4,7]],[[3,5,6],[1,7,8]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3,flags=['buffered'],op_dtypes=["S"]):
  print(i)

[[[1 2 4]
  [3 4 7]]

 [[3 5 6]
  [1 7 8]]]
3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'4')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'7')
np.bytes_(b'3')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'1')
np.bytes_(b'7')
np.bytes_(b'8')


**ndenumerate() function**    to create the index value    

In [77]:
var3 = np.array([[[1,2,4],[3,4,7]],[[3,5,6],[1,7,8]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
  print(i,d)

[[[1 2 4]
  [3 4 7]]

 [[3 5 6]
  [1 7 8]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 4
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 7
(1, 0, 0) 3
(1, 0, 1) 5
(1, 0, 2) 6
(1, 1, 0) 1
(1, 1, 1) 7
(1, 1, 2) 8


# The Difference bitween Copy & View in NUMPY ARRAYS

In [83]:
import numpy as np

var = np.array([1,2,3,4])
co = var.copy()
var[1] = 40

print("var :",var)
print("copy :",co)

var : [ 1 40  3  4]
copy : [1 2 3 4]


In [84]:
x = np.array([1,2,3,4])
vi = x.view()
x[1] = 40

print("x :",x)
print("view :",vi)

x : [ 1 40  3  4]
view : [ 1 40  3  4]


# JOIN AND SPLIT FUNCTIONS IN NUMPY ARRAYS

**JOIN ARRAY**

In [85]:
import numpy as np

var = np.array ([1,2,3,4])
var1 = np.array ([5,6,7,8])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 5 6 7 8]


In [89]:
vr = np.array ([[11,22],[33,44]])
vr1 = np.array ([[55,66],[77,88]])
print(vr)
print()
print(vr1)
print()
ar_new = np.concatenate((vr,vr1),axis=1)
print(ar_new)

[[11 22]
 [33 44]]

[[55 66]
 [77 88]]

[[11 22 55 66]
 [33 44 77 88]]


In [90]:
vr = np.array ([[[11,22],[33,44]]])
vr1 = np.array ([[[55,66],[77,88]]])
print(vr)
print()
print(vr1)
print()
ar_new = np.concatenate((vr,vr1),axis=1)
print(ar_new)

[[[11 22]
  [33 44]]]

[[[55 66]
  [77 88]]]

[[[11 22]
  [33 44]
  [55 66]
  [77 88]]]


**using stack fucntion**

In [104]:
var_1 = np.array ([1,2,3,4])
var_2 = np.array ([5,6,7,8])

a_new = np.stack((var_1,var_2))
a_new4 = np.stack((var_1,var_2),axis = 1)
a_new1 = np.hstack((var_1,var_2))   # row
a_new2 = np.vstack((var_1,var_2))   #column
a_new3 = np.dstack((var_1,var_2))   #height

print(a_new)
print()
print(a_new4)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


**split array**

In [107]:
import numpy as np


var = np.array ([2,3,4,5,6,7])
print(var)
print()
ar = np.array_split(var,3)
print(ar)
print()
print(type(ar))
print(ar[0])
print(ar[1])
print(ar[2])


[2 3 4 5 6 7]

[array([2, 3]), array([4, 5]), array([6, 7])]

<class 'list'>
[2 3]
[4 5]
[6 7]


In [108]:
var1 = np.array ([[2,3],[4,5],[6,7]])
print(var1)
print()
ar = np.array_split(var1,3)
print(ar)
print()
print(type(ar))
print(ar[0])
print(ar[1])
print(ar[2])

[[2 3]
 [4 5]
 [6 7]]

[array([[2, 3]]), array([[4, 5]]), array([[6, 7]])]

<class 'list'>
[[2 3]]
[[4 5]]
[[6 7]]


# NUMPY ARRAYS FUNCTIONS
1. **SEARCH**
2. **SORT**
3. **SEARCH SORTED**
4. **FILTER**

**SEARCH**

In [116]:
import numpy as np


var = np.array([1,9,2,6,3,4,7,5,2,6,7, 1, 8])
# index.        0 1 2 3 4 5 6 7 8 9 10 11 12

x = np.where(var==2)
print(x)
print()
y = np.where(var%2==0)
print(y)

(array([2, 8]),)

(array([ 2,  3,  5,  8,  9, 12]),)


**SEARCH SORTED**

In [120]:
var1 = np.array([1,2,3,4,6,7,8,9,10,11,12])
# index.         0 1 2 3 4 5 6 7 8  9  10

x1 = np.searchsorted(var1, 5)
print(x1)

x2 = np.searchsorted(var1, [5,6,7], side = "right")   # start searching from right side
print(x2)


4
[4 5 6]


**SORT ARRAY**

In [121]:
var2 = np.array([1,9,2,6,3,4,7,5,2,6,7, 1, 8])
# index         0 1 2 3 4 5 6 7 8 9 10 11 12

print(np.sort(var2))

[1 1 2 2 3 4 5 6 6 7 7 8 9]


In [122]:
var3 = np.array(["A","G","Y","O","V"])
# index           0   1   2   3   4

print(np.sort(var3))

['A' 'G' 'O' 'V' 'Y']


In [123]:
var4 = np.array([[1,9,2],[6,3,4],[7,5,2],[6,7,1]])
# index         0 1 2 3 4 5 6 7 8 9 10 11 12

print(np.sort(var4))

[[1 2 9]
 [3 4 6]
 [2 5 7]
 [1 6 7]]


**FILTER ARRAY**

In [126]:
var5 = np.array(["a","s","f","i","u","m"])

f = [True,False,True,False,False,True]

new_a = var5[f]
print(new_a)
print()
print(var5[f])
print(type(new_a))

['a' 'f' 'm']

['a' 'f' 'm']
<class 'numpy.ndarray'>


# ARRAY MANIPULATION FUNCTIONS

**SHUFFLE FUNCTION**

In [131]:
import numpy as np

var = np.array ([1,2,3,4,5,6,7,8,9])

np.random.shuffle(var)
print(var)

[3 8 1 2 7 5 4 6 9]


**UNIQUE FUNCTION**

In [135]:
var1 = np.array ([1,2,3,4,5,6,2,6,2,7,2,8,2,9,3,5,3,6,3,7])
x = np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  2,  3,  4,  5,  9, 11, 13]), array([1, 5, 4, 1, 2, 3, 2, 1, 1]))


**RESIZE FUNCTION**

In [141]:
var2 = np.array ([1,2,3,4,5,6,2,6,2,7,2,8,2,9,3,5,3,6,3,7])
y = np.resize(var2,(6,6))
print(y)

[[1 2 3 4 5 6]
 [2 6 2 7 2 8]
 [2 9 3 5 3 6]
 [3 7 1 2 3 4]
 [5 6 2 6 2 7]
 [2 8 2 9 3 5]]


**FLATTEN FUNCTION**

In [148]:
var3 = np.array ([1,2,3,4,5,6,2,6,2,7,2,8,2,9,3,5,3,6,3,7])
y = np.resize(var3,(7,3))
print(y)
print()
print(y.flatten())
print()
print(y.flatten(order="F"))
print()
print(y.flatten(order="C"))
print()
print(y.flatten(order="A"))
print()
print(y.flatten(order="K"))

[[1 2 3]
 [4 5 6]
 [2 6 2]
 [7 2 8]
 [2 9 3]
 [5 3 6]
 [3 7 1]]

[1 2 3 4 5 6 2 6 2 7 2 8 2 9 3 5 3 6 3 7 1]

[1 4 2 7 2 5 3 2 5 6 2 9 3 7 3 6 2 8 3 6 1]

[1 2 3 4 5 6 2 6 2 7 2 8 2 9 3 5 3 6 3 7 1]

[1 2 3 4 5 6 2 6 2 7 2 8 2 9 3 5 3 6 3 7 1]

[1 2 3 4 5 6 2 6 2 7 2 8 2 9 3 5 3 6 3 7 1]


**RAVEL FUNCTION**

In [151]:
var4 = np.array ([1,2,3,4,5,6,2,6,2,7,2,8,2,9,3,5,3,6,3,7])
y = np.resize(var4,(7,3))
print(y)

print()
print("Flatten :", y.flatten(order="F"))
print("Ravel :", np.ravel(y,order="F"))


[[1 2 3]
 [4 5 6]
 [2 6 2]
 [7 2 8]
 [2 9 3]
 [5 3 6]
 [3 7 1]]

Flatten : [1 4 2 7 2 5 3 2 5 6 2 9 3 7 3 6 2 8 3 6 1]
Ravel : [1 4 2 7 2 5 3 2 5 6 2 9 3 7 3 6 2 8 3 6 1]


# INSERT & DELETE FUNCTIONS

**INSERT**

In [19]:
import numpy as np

var = np.array ([1,2,3,4,5])
print(var)
print()

var1 = np.insert(var,2,30)   # this won't accept float value, only int
print(var1)
print()

x= np.append(var,6)   # with append function we can insert float value but it will add at last
print(x)
print()

y = np.append(var, [6,7.8,8.9])
print(y)


[1 2 3 4 5]

[ 1  2 30  3  4  5]

[1 2 3 4 5 6]

[1.  2.  3.  4.  5.  6.  7.8 8.9]


In [11]:
var2 = np.array ([[1,2,3],[4,5,6]])

var3 = np.insert(var2,2,10,axis=1)
print(var3)
print()
var5= np.insert(var2,2,[10,11],axis=1)
print(var5)
print()
var4 = np.insert(var2,2,20,axis=0)
print(var4)

[[ 1  2 10  3]
 [ 4  5 10  6]]

[[ 1  2 10  3]
 [ 4  5 11  6]]

[[ 1  2  3]
 [ 4  5  6]
 [20 20 20]]


**DELETE**

In [23]:
var1 = np.array([1,2,3,4,5])
print(var1)
print()

d = np.delete(var1,2)
print(d)

[1 2 3 4 5]

[1 2 4 5]


# MATRIX IN NUMPY ARRAY

In [25]:
import numpy as np

var = np.matrix([[1,2],[4,5]])
print(var)
print(type(var))
print()
var1 = np.array([[1,2],[4,5]])
print(var1)
print(type(var1))

[[1 2]
 [4 5]]
<class 'numpy.matrix'>

[[1 2]
 [4 5]]
<class 'numpy.ndarray'>


In [27]:
var2 = np.matrix([[1,2],[4,5]])
var3 = np.matrix([[1,2],[4,5]])
print(var2)
print()
print(var3)
print()
print(var2+var3)
print()
print(var2-var3)
print()
print(var2*var3)
print()
print(var2.dot(var3))
print()
print(var2/var3)

[[1 2]
 [4 5]]

[[1 2]
 [4 5]]

[[ 2  4]
 [ 8 10]]

[[0 0]
 [0 0]]

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]

[[1. 1.]
 [1. 1.]]


**MATRIX FUNCTION IN NUMPY**

In [48]:
import numpy as np

var = np.matrix([[1,2],[7,4]])
print(var)
print()
x = np.transpose(var)
print(x)
print()
print(var.T)   # naother methode of transpose
print()
print(np.swapaxes(var,0,1))
print()
print(np.power(var,2))
print()
print(np.linalg.matrix_power(var,3))
print()
print(np.invert(var))
print()
print(np.linalg.det(var))
print()
print(np.linalg.inv(var))

[[1 2]
 [7 4]]

[[1 7]
 [2 4]]

[[1 7]
 [2 4]]

[[1 7]
 [2 4]]

[[ 1  4]
 [49 16]]

[[ 85  70]
 [245 190]]

[[-2 -3]
 [-8 -5]]

-9.999999999999998

[[-0.4  0.2]
 [ 0.7 -0.1]]
